[package]
name = "x55-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epoll = "4.3.3"
evdev = "0.12.1"
nix = { version = "0.28.0", features = [ "fs", "event" ] }
