#!/sbin/openrc-run

name="powkiddy-x55-mapper"
command="/usr/bin/x55-mapper"
pidfile="/var/run/x55-mapper.pid"
command_background=true

depend()
{
	need localmount udev
	keyword -docker -lxc -openvz -prefix -systemd-nspawn -uml -vserver -xenu
}

start_pre()
{
	# Setup kernel support for user level drivers (input subsystem)
	if [ ! -e /dev/uinput ]; then
		if ! modprobe -q uinput; then
			eerror "The uinput module needs to be loaded by " \
				"the x55-mapper service or built in."
		fi
	fi
}
